apiVersion: v1
kind: ConfigMap
metadata:
  name: nfl-model-config
  namespace: production
data:
  config.yaml: |
    model:
      ensemble_weights: [0.6, 0.4]
      kelly_fraction: 0.25
      max_bet_fraction: 0.03
      min_edge_threshold: 0.02
      n_splits: 5
      early_stopping_rounds: 100
    
    monitoring:
      psi_warning_threshold: 0.15
      psi_critical_threshold: 0.25
      performance_degradation_threshold: 0.1
      roi_alert_threshold: -0.05
      enable_alerts: true
      report_frequency: daily
    
    online_learning:
      learning_rate: 0.01
      batch_size: 32
      update_frequency: weekly
      drift_threshold: 0.3
      adaptive_learning: true
    
    api:
      cache_ttl: 3600
      max_batch_size: 100
      rate_limit: 1000
      timeout_seconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nfl-betting-model-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.nfl-betting-model.com
    secretName: nfl-model-tls
  rules:
  - host: api.nfl-betting-model.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nfl-betting-model-service
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-model-secrets
  namespace: production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYi9uZmw=  # postgresql://user:pass@db/nfl
  api-key: YWJjZGVmZ2hpams=  # abcdefghijk
  model-storage-key: czM6Ly9idWNrZXQvbW9kZWxz  # s3://bucket/models
